# Generated by Django 5.1 on 2024-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailscanresult',
            name='email_id',
        ),
        migrations.AddField(
            model_name='emailscanresult',
            name='body',
            field=models.TextField(default='No body'),
        ),
        migrations.AlterField(
            model_name='emailscanresult',
            name='attachment_scan_results',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailscanresult',
            name='header_analysis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailscanresult',
            name='links_scan_results',
            field=models.TextField(),
        ),
    ]
