# Generated by Django 5.1 on 2024-10-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scanner', '0003_remove_emailscanresult_attachment_scan_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailscanresult',
            name='ml_analysis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailscanresult',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
